server_id:
  type: string
  default: " "
  description: 
    en: 'The server ID, e.g. 123456789012345678'
theme_color:
  type: string
  default: " "
  description: 
    en: "Set your widget to 'light' or 'dark'"    
